### ISSUE TITLE
Code does not recognize the Draft: namespace

### ISSUE THREAD

**Issue by zanhecht** [openzim/wikimedia_wp1_bot#1]
The bot, likely because it grabs namespace names from an outdated database originally from toolserver, does not recognize the Draft: namespace. As a result, a link to [[Draft:Example]] is inserted into the list page as [[::Example]]. Not only does this link not work, it clogs up https://en.wikipedia.org/wiki/Special:LintErrors/multi-colon-escape

**Comment by kelson42** [comment]
@zanhecht What is the problematic symptom?

**Comment by zanhecht** [comment]
See
https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Draft_links

The tool doesn't appear to know the name of the draft namespace on the
English Wikipedia, so an article that should be linked as [[:Draft:
Example]] is being linked as [[:: Example]].

This is filling up the lint error logs designed to catch wikilinks with two
leading colons, which the latest version mediawiki no longer recognizes as
valid links.


On Oct 11, 2017 1:41 AM, "Kelson" <notifications@github.com> wrote:

@zanhecht <https://github.com/zanhecht> What is the problematic symptom?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openzim/wikimedia_wp1_bot/issues/1#issuecomment-335688990>,
or mute the thread

**Comment by zanhecht** [comment]
Actually, it seems to fail on any namespace other than the main namespace (likely because it is trying to pull the names from the toolserver database that no longer exists). Therefore, any assessed page not in mainspace (such as templates, categories, files, etc.) will produce a broken link with two leading colons.

**Comment by kelson42** [comment]
@zanhecht I have updated the database of namespaces (added "Draft" related namesapces). So, I guess it should work now (maybe wait 1/2 days to get the page updated). Please re-open the ticket if not.
