### ISSUE TITLE
global_articles table update is currently disabled

### ISSUE THREAD

**Issue by audiodude** [openzim/wikimedia_wp1_bot#12]
You can see it copied from the original Perl and commented out here:
https://github.com/openzim/wikimedia_wp1_bot/blob/master/lucky/lucky/logic/project.py#L358

This is likely to cause the Global Table (https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/OverallArticles) to have incorrect data.

**Comment by audiodude** [comment]
I don't see any reason why to not turn this back on.

**Comment by kelson42** [comment]
@audiodude Yes, and I think you already have.
