### ISSUE TITLE
Certain articles are always reassessed in logs

### ISSUE THREAD

**Issue by kelson42** [openzim/wikimedia_wp1_bot#3]
Like "Clément Roques" in https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Catholicism_articles_by_quality_log#Reassessed

More details at https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index/Archive_8#Long_term_snafu_caused_by_duplicate_project_tags

This problem might be related too https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Bot_running,_but_includes_many_articles_not_for_that_date

**Comment by kelson42** [comment]
@audiodude The problem I see now, is that this page is meanwhil not updated at all anymore.

**Comment by audiodude** [comment]
That's right. As I mentioned in #7, an admin has protected the logging tables to prevent the old bot from updating them because it was so broken.

I believe the solution is the full re-write unfortunately.

**Comment by kelson42** [comment]
The codebase generating that problem does not exist anymore, but the problem is not fixed. That said, this ticket is superseeded by #89.
