### ISSUE TITLE
Database SQL schema

### ISSUE THREAD

**Issue by kelson42** [openzim/wikimedia_wp1_bot#34]
I don't know/see where is the Database initialisation SQL file. We should have one to be able to resetup the project in case we "loose" our database.

**Comment by audiodude** [comment]
We have a couple of backups that I made before enabling the new bot for the first time. I'm sure I could extract a schema.sql from that. Shall I put it in the root directory?

**Comment by kelson42** [comment]
@audiodude Thx, that would be perfect to have the schema in a subdirectory `setup`.

**Comment by audiodude** [comment]
Fixed with https://github.com/openzim/wikimedia_wp1_bot/commit/0172937176f3cc8e27de8ca03de261df3de2633b
