### ISSUE TITLE
New bot doesn't update project "Count" page

### ISSUE THREAD

**Issue by audiodude** [openzim/wikimedia_wp1_bot#43]
There is a script that is supposed to update [this Wikipedia Page](https://en.wikipedia.org/wiki/User:WP_1.0_bot/Data/Count).

It lived at:
https://github.com/openzim/wikimedia_wp1_bot/blob/toolforge/backend/copy_count.pl

We are currently not doing any such action with the new bot (though it would be easy to add back in), but it doesn't seem to matter because the old bot script seemed to be broken for some time. If you look in the edit history of that page, it is always empty.

**Comment by kelson42** [comment]
@walkerma Do you have an opinion on this?

**Comment by walkerma** [comment]
I just saw this- sorry!  It's hard for me to answer, because I don't remember that wiki page even existing.  I see from the history that it recorded the total no. of wikiprojects, but I don't know the purpose of that.  I'm guessing Carl needed it for some reason.  Do you need me to do anything?

**Comment by audiodude** [comment]
Just needed your knowledge on the matter.

Like I said, it's been blank for ages (before we started the new bot) so I don't think it matters. Let's keep this issue for reference and move on without it.

**Comment by kelson42** [comment]
@audiodude @walkerma This page is still in use [here](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Index) to say how many wikiprojects we have. The page is currently broken because we have an empty template.
